### PR TITLE
There is a null pointer error. The [objectname] here may be null. It needs to be pre judged whether it is null

### PR DESCRIPTION
**Pull request by dh20**
What changes were proposed in this pull request?
 fix a null error.
Why are the changes needed?

fix bug,Improve user experience

Does this PR introduce any user-facing change?
not

How was this patch tested?
not

### CODE REVIEW

**Comment by dh20** [comment]
@barnharts4 Can you review this PR for me？ths！

**Review by javsanbel2 — APPROVED** [review]

**Comment by javsanbel2** [comment]
Hey @dh20, thanks for your contribution, I am running some tests before merging the branch 👍

**Comment by dh20** [comment]
@javsanbel2 Thanks. I looked at the error generated by the test just now. I found that it has nothing to do with my changes. It seems that it is an error downloaded by some plug-ins during Maven's construction

**Comment by javsanbel2** [comment]
Hey @dh20, we are checking the error in our GitHub action workflow, sorry for the inconvenience, I will get back to you as soon as possible.

**Comment by dh20** [comment]
@javsanbel2 ok,thanks,We look forward to your reply!!!

**Comment by dh20** [comment]
@javsanbel2  Hi, sir, have you got any results yet

**Comment by dh20** [comment]
@abhimanyugupta07 can you help me review it? thanks !!!

**Comment by abhimanyugupta07** [comment]
Sorry @dh20. We are still sorting out some issues with the build and release process for our open source projects but we will merge this PR and will try roll out a new release soon.

**Comment by abhimanyugupta07** [comment]
@dh20 We have cut a 3.10.7 release. You can use that now.

**Comment by dh20** [comment]
@abhimanyugupta07 OK, sir, I hope that the issues with the build and release process for your open source projects can be repaired as soon as possible

**Comment by abhimanyugupta07** [comment]
@dh20 The issue is resolved. We have released version `3.10.7` that you can use.

**Pull request merged**
