### PR TITLE
Hive 3.x backport  readonly and ratelimit feature

### PR DESCRIPTION
**Pull request by flaming-archer**
### :pencil: Description
Make sure that the 3.x branch and the main branch are not too far apart.
### :link: Related Issues
https://github.com/ExpediaGroup/waggle-dance/discussions/319

### CODE REVIEW

**Comment by flaming-archer** [comment]
@jmnunezizu @patduin pls take a look at it.  The audit log, `HMSHandler.getThreadLocalIpAddress` was removed because of this method in hive 3.x is not public.  It's not worth writing reflections for it alone.

**Comment by flaming-archer** [comment]
This failed test case should have nothing to do with submission:`Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project waggle-dance-rpm: Failed to deploy artifacts: Could not transfer artifact com.hotels:waggle-dance-boot:jar:exec:4.0.0-20240626.031244-2 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots): authentication failed for https://oss.sonatype.org/content/repositories/snapshots/com/hotels/waggle-dance-boot/4.0.0-SNAPSHOT/waggle-dance-boot-4.0.0-20240626.031244-2-exec.jar, status: 401 Unauthorized -> [Help 1]`

**Review by patduin — APPROVED** [review]
Thanks this is looking good, test all ran green.

**Comment by flaming-archer** [comment]
@jmnunezizu Could you pls review this and merge it.

**Review by jmnunezizu — APPROVED** [review]

**Comment by jmnunezizu** [comment]
@flaming-archer – thanks for porting the new features to the Hive 3.x branch!

**Pull request merged**
